
---@class SessionOpts
---@field project_path string
---@field global_path string
---
---@class Continuum.BuiltinCustom
---@field qf boolean
---@field codecompanion boolean
---
---@class Continuum.Config
---@field use_git_branch boolean
---@field use_git_host boolean
---@field auto_restore boolean
---@field auto_save boolean
---@field auto_restore_on_branch_change boolean
---@field log_level integer
---@field mappings Continuum.Mappings
---@field custom_builtin Continuum.BuiltinCustom
---@field custom table<Continuum.CustomHandler>
---
---@class Continuum.Mappings
---@field delete_session? table

---@class Continuum.PickerData
---@field base string
---@field branch string
---@field name string
---@field path string
---
---@class Continuum.PickerModule
---@field register function
---@field enabled boolean
---@field pick function
---@field name string
---
---@class Continuum.SearchOpts
---@field all? boolean
---@field picker? "telescope" | "snacks" | "select"

---@class Continuum.CustomHandler
---@field load function
---@field save function 
---@field init function
---@field config any 
---@field id string
