name: test

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  tests:
    name: Run tests
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        neovim_version: ["v0.11.0"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Setup neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
      - name: Run tests
        run: |
          make test
